services:
  dev:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci
    image: keboola/php-db-import-export
    platform: linux/amd64
    working_dir: /code
    volumes:
      - .:/code
      - ../TableBackendUtils:/code/packages/TableBackendUtils
    environment:
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_CONTAINER_NAME
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_S3_KEY
      - AWS_REGION
      - BUILD_PREFIX
      - STORAGE_TYPE
      - GCS_CREDENTIALS
      - GCS_BUCKET_NAME
      - GCS_INTEGRATION_NAME
      - BQ_KEY_FILE
      - BQ_BUCKET_NAME
      - SUITE

  ci:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci
    image: ci-db-import-export
    platform: linux/amd64
    working_dir: /code
    volumes:
      - .:/code
      - ../TableBackendUtils:/code/packages/TableBackendUtils
    environment:
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_CONTAINER_NAME
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_S3_KEY
      - AWS_REGION
      - BUILD_PREFIX
      - STORAGE_TYPE
      - GCS_CREDENTIALS
      - GCS_BUCKET_NAME
      - GCS_INTEGRATION_NAME
      - BQ_KEY_FILE
      - BQ_BUCKET_NAME
      - SUITE
