<?php

declare(strict_types=1);

namespace Keboola\Db\ImportExport;

use Keboola\Db\ImportExport\Backend\Helper\BackendHelper;

class ExportOptions implements ExportOptionsInterface
{
    public const MANIFEST_AUTOGENERATED = true;
    public const MANIFEST_SKIP = false;
    public const EXPORT_FILE_TYPE_CSV = 'csv';
    public const EXPORT_FILE_TYPE_PARQUET = 'parquet';
    public const EXPORT_FILE_TYPE_AVRO = 'avro';

    private bool $isCompressed;

    private string $exportId;

    private bool $generateManifest;

    private string $fileType;

    public function __construct(
        bool $isCompressed = false,
        bool $generateManifest = self::MANIFEST_SKIP,
        ?string $fileType = self::EXPORT_FILE_TYPE_CSV
    ) {
        $this->isCompressed = $isCompressed;
        $this->exportId = BackendHelper::generateRandomExportPrefix();
        $this->generateManifest = $generateManifest;
        $this->fileType = $fileType;
    }

    public function getExportId(): string
    {
        return $this->exportId;
    }

    public function isCompressed(): bool
    {
        return $this->isCompressed;
    }

    public function generateManifest(): bool
    {
        return $this->generateManifest === self::MANIFEST_AUTOGENERATED;
    }

    public function getFileType(): string
    {
        return $this->fileType;
    }
}
